name: Plan EC2

on:
  pull_request:
    paths:
      - 'ec2/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  plan-dev:
    name: 'Terraform PLAN'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: 'ec2'

    defaults:
      run: 
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }} 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt 

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color